mailer:
  default_email: 'DEFAULT_EMAIL'
  default_email_name: 'DEFAULT_EMAIL_NAME'
  forgot_password_mail_template_id: 'FORGOT_PASSWORD_MAIL_TEMPLATE_ID'

mongodb:
  uri: 'MONGODB_URI'

temporal:
  server_address: 'TEMPORAL_SERVER_ADDRESS'

web_app_host: 'WEB_APP_HOST'

inspectlet:
  key: 'INSPECTLET_KEY'

datadog:
  api_key: 'DATADOG_API_KEY'
  site_name: 'DATADOG_SITE'
  app_name: 'DATADOG_APP_NAME'
  log_level: 'DATADOG_LOG_LEVEL'

sendgrid:
  api_key: 'SENDGRID_API_KEY'

twilio:
  account_sid: 'TWILIO_ACCOUNT_SID'
  auth_token: 'TWILIO_AUTH_TOKEN'
  messaging_service_sid: 'TWILIO_MESSAGING_SERVICE_SID'

public:
  datadog:
    applicationId: 'DATADOG_APPLICATION_ID'
    clientToken: 'DATADOG_CLIENT_TOKEN'
    enabled: 'DATADOG_ENABLED'
    env: 'DATADOG_ENV'
    service: 'DATADOG_SERVICE'
    sessionReplaySampleRate: 'DATADOG_SESSION_REPLAY_SAMPLE_RATE'
    sessionSampleRate: 'DATADOG_SESSION_SAMPLE_RATE'
    site: 'DATADOG_SITE'
  default_otp:
    enabled: 'DEFAULT_OTP_ENABLED'
    code: 'DEFAULT_OTP_CODE'
    whitelisted_phone_number: 'DEFAULT_OTP_WHITELISTED_PHONE_NUMBER'  # e.g., "9999999999"
