logger:
  transports: ['console']

mongodb:
  uri: 'mongodb://localhost:27017/frm-boilerplate-dev'

temporal:
  server_address: 'localhost:7233'

sms:
  enabled: false

is_server_running_behind_proxy: false

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  default_otp:
    enabled: true
    code: '1234'

account:
  enable_bootstrap_tasks: true
  create_test_user_account: true
  test_user:
    first_name: "Dev"
    last_name: "User"
    username: "dev@example.com"
    password: "devpassword"

BOOTSTRAP_APP: true
