logger:
  transports:
    - 'console'
    - 'datadog'

sms:
  enabled: true

is_server_running_behind_proxy: true

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  default_otp:
    enabled: true
    code: '1234'

account:
  enable_bootstrap_tasks: true
  create_test_user_account: true
  test_user:
    first_name: "Preview"
    last_name: "User"
    username: "preview@example.com"
    password: "previewpassword"

BOOTSTRAP_APP: true
